export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const RECEIVE_CURRENCIES = 'RECEIVE_CURRENCIES';
export const CHANGE_TRANSPLANTS_COUNT = 'CHANGE_TRANSPLANTS_COUNT';
export const CHANGE_TRANSPLANTS_COUNT_SINGLE = 'CHANGE_TRANSPLANTS_COUNT_SINGLE';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
